### ISSUE TITLE
テストを実行するとWebdrivers::VersionErrorが発生する

### ISSUE THREAD

**Issue by JunichiIto** [JunichiIto/everydayrails-rspec-jp-2022#18]
```
$ bundle exec rspec

HomeController
  returns a 200 response
  #index
    responds successfully

NotesController
  #index
    searches notes by the provided keyword

ProjectsController
  #index
    as an authenticated user
      responds successfully
    as a guest
      returns a 302 response
      redirects to the sign-in page
  #show
    as an authorized user
      responds successfully
    as an unauthorized user
      redirects to the dashboard
  #create
    as an authenticated user
      with valid attributes
        adds a project
      with invalid attributes
        does not add a project
    as a guest
      returns a 302 response
      redirects to the sign-in page
  #update
    as an authorized user
      updates a project
    as an unauthorized user
      does not update the project
      redirects to the dashboard
    as a guest
      returns a 302 response
      redirects to the sign-in page
  #destroy
    as an authorized user
      deletes a project
    as an unauthorized user
      does not delete the project
      redirects to the dashboard
    as a guest
      returns a 302 response
      redirects to the sign-in page
      does not delete the project
  #complete
    as an authenticated user
      an unsuccessful completion
        redirects to the project page
        sets the flash
        doesn't mark the project as completed

TasksController
  #show
    responds with JSON formatted output
  #create
    responds with JSON formatted output
    adds a new task to the project
    requires authentication

GeocodeUserJob
  calls geocode on the user

UserMailer
  welcome_email
    sends a welcome email to the user's email address
    sends from the support email address
    sends with the correct subject
    greets the user by first name
    reminds the user of the registered email address

Note
  is valid with a user, project, and message
  is invalid without a message
  has one attached attachment
  delegates name to the user who created it
  search message for a term
    when a match is found
      returns notes that match the search term
    when no match is found
      returns an empty collection

Project
  is expected to validate that :name is case-sensitively unique within the scope of :user_id
  can have many notes
  late status
    is late when the due date is past today
    is on time when the due date is today
    is on time when the due date is in the future

Task
  is valid with a project and name
  is invalid without a project
  is invalid without a name

User
  has a valid factory
  is valid with a first name, last name and email, and password
  is expected to validate that :first_name cannot be empty/falsy
  is expected to validate that :last_name cannot be empty/falsy
  is expected to validate that :email cannot be empty/falsy
  is expected to validate that :email is case-insensitively unique
  returns a user's full name as a string
  sends a welcome email on account creation
  performs geocoding

Home page
  responds successfully

Projects API
  loads a project
  creates a project

Projects
  as an authenticated user
    with valid attributes
      adds a project
    with invalid attributes
      does not add a project

Notes
  user uploads an attachment

Projects
  user creates a new project
  user completes a project

Sign in
  user signs in

Sign-ups
  user successfully signs up

Tasks
  user toggles a task (FAILED - 1)

Failures:

  1) Tasks user toggles a task
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: visit root_path
          
          Webdrivers::VersionError:
            Unable to find latest point release version for 115.0.5790. You appear to be using a non-production version of Chrome. Please set `Webdrivers::Chromedriver.required_version = <desired driver version>` to a known chromedriver version: https://chromedriver.storage.googleapis.com/index.html
          # ./spec/system/tasks_spec.rb:24:in `go_to_project'
          # ./spec/system/tasks_spec.rb:14:in `block (2 levels) in <main>'
          # ------------------
          # --- Caused by: ---
          # Webdrivers::NetworkError:
          #   Net::HTTPClientException: 404 "Not Found" with https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
          #   ./spec/system/tasks_spec.rb:24:in `go_to_project'

     1.2) Failure/Error: raise VersionError, msg
          
          Webdrivers::VersionError:
            Unable to find latest point release version for 115.0.5790. You appear to be using a non-production version of Chrome. Please set `Webdrivers::Chromedriver.required_version = <desired driver version>` to a known chromedriver version: https://chromedriver.storage.googleapis.com/index.html
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/webdrivers-5.2.0/lib/webdrivers/chromedriver.rb:83:in `rescue in latest_point_release'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/webdrivers-5.2.0/lib/webdrivers/chromedriver.rb:65:in `latest_point_release'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/webdrivers-5.2.0/lib/webdrivers/chromedriver.rb:39:in `block in latest_version'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/webdrivers-5.2.0/lib/webdrivers/common.rb:166:in `with_cache'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/webdrivers-5.2.0/lib/webdrivers/chromedriver.rb:37:in `latest_version'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/webdrivers-5.2.0/lib/webdrivers/common.rb:122:in `download_version'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/webdrivers-5.2.0/lib/webdrivers/common.rb:126:in `download_url'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/webdrivers-5.2.0/lib/webdrivers/common.rb:98:in `update'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/webdrivers-5.2.0/lib/webdrivers/chromedriver.rb:156:in `block in <main>'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/service.rb:99:in `binary_path'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/service.rb:73:in `initialize'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/service.rb:32:in `new'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/service.rb:32:in `chrome'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/driver.rb:340:in `service_url'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/driver.rb:321:in `create_bridge'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/driver.rb:47:in `new'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/driver.rb:47:in `for'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver.rb:88:in `for'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara/selenium/driver.rb:83:in `browser'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara/selenium/driver.rb:161:in `save_screenshot'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara/session.rb:747:in `block in save_screenshot'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara/session.rb:747:in `save_screenshot'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:99:in `save_image'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:36:in `take_screenshot'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:45:in `take_failed_screenshot'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4/lib/action_dispatch/system_testing/test_helpers/setup_and_teardown.rb:8:in `before_teardown'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-rails-6.0.1/lib/rspec/rails/example/system_example_group.rb:110:in `call'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-rails-6.0.1/lib/rspec/rails/example/system_example_group.rb:110:in `block (2 levels) in <module:SystemExampleGroup>'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:372:in `run'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:529:in `block in run_owned_hooks_for'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:528:in `each'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:528:in `run_owned_hooks_for'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:615:in `block in run_example_hooks_for'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:614:in `each'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:614:in `run_example_hooks_for'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:485:in `run'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:518:in `run_after_example'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:283:in `block in run'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `block in run'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:352:in `call'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-rails-6.0.1/lib/rspec/rails/example/system_example_group.rb:120:in `block (2 levels) in <module:SystemExampleGroup>'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:390:in `execute_with'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:352:in `call'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-rails-6.0.1/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:390:in `execute_with'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:352:in `call'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `run'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:259:in `run'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `map'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `run_examples'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:607:in `run'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `map'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/reporter.rb:74:in `report'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:115:in `run_specs'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:89:in `run'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:71:in `run'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:45:in `invoke'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.0/exe/rspec:4:in `<top (required)>'
          # /Users/jnito/.rbenv/versions/3.2.0/bin/rspec:25:in `load'
          # /Users/jnito/.rbenv/versions/3.2.0/bin/rspec:25:in `<top (required)>'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:58:in `load'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:23:in `run'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/cli.rb:492:in `exec'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/cli.rb:34:in `dispatch'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/cli.rb:28:in `start'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/exe/bundle:45:in `block in <top (required)>'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
          # /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/exe/bundle:33:in `<top (required)>'
          # /Users/jnito/.rbenv/versions/3.2.0/bin/bundle:25:in `load'
          # /Users/jnito/.rbenv/versions/3.2.0/bin/bundle:25:in `<main>'
          # 
          #   Showing full backtrace because every line was filtered out.
          #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
          #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
          # ------------------
          # --- Caused by: ---
          # Webdrivers::NetworkError:
          #   Net::HTTPClientException: 404 "Not Found" with https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
          #   /Users/jnito/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/webdrivers-5.2.0/lib/webdrivers/network.rb:19:in `get'

Finished in 10.9 seconds (files took 1.35 seconds to load)
70 examples, 1 failure

Failed examples:

rspec ./spec/system/tasks_spec.rb:12 # Tasks user toggles a task
```

**Comment by JunichiIto** [comment]
この問題に遭遇した場合は以下の手順で対応してください。

1. Gemfileを開いて`gem "webdrivers"`の行を削除する
2. `bundle update selenium-webdriver capybara`を実行する

Everyday Railsのサンプルコードの修正は本文の修正と同時に実施します。
もうしばらくお待ちください。

**Comment by JunichiIto** [comment]
こちらのissueは対応済みです。
https://github.com/JunichiIto/everydayrails-rspec-jp-2022/commit/1ea11152d2711a51b1cf2a0aba4ac576518153f5
